CREATE TABLE scheduler (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date CHAR(8) NOT NULL DEFAULT "",
  title TEXT NOT NULL DEFAULT "",
  comment TEXT NOT NULL DEFAULT "",
  repeat VARCHAR(128) NOT NULL DEFAULT ""
);
CREATE INDEX task_date ON scheduler (date);

